const { apiRequest } = require("../support/page_objects/apiRequest")
const { board } = require("../support/page_objects/board")

describe('Trello Board', () => {

    it('Create A Board', () => {
        apiRequest.createBoard('First Board')
        cy.visit('/')
        board.clickOnCreatedBoard()
    })
    it('Create A List', () => {
        apiRequest.createBoard('Second Board')
        apiRequest.createList('TODO')
        cy.visit('/')
        board.clickOnCreatedBoard()
        board.findCreatedList()
    })
    it('Create a Card', () => {
        apiRequest.createBoard('Third Board')
        apiRequest.createList('TestList')
        apiRequest.createCard('Task 1')
        cy.visit('/')
        board.clickOnCreatedBoard()
        board.clickOnCreatedCard()
    })
    it('Move Card', () => {
        apiRequest.createBoard('Fourth Board')
        cy.visit('/')
        board.clickOnCreatedBoard()
        apiRequest.createList('TestList')
        apiRequest.createCard('Task 1')
        cy.reload()
        board.findCreatedCard()
        apiRequest.setExistingListAsVariable(2)
        apiRequest.moveCardFromCreatedListToExistingList()
        cy.reload()
        board.findMovedCard()
    })
    it('Delete Card', () => {
        apiRequest.createBoard('Fifth Board')
        apiRequest.createList('List')
        apiRequest.createCard('To delete')
        cy.visit('/')
        board.clickOnCreatedBoard()
        board.findCreatedCard()
        apiRequest.deleteCard()
        board.deletedCardNotExist()
    })
    it('Delete Board', () => {
        apiRequest.createBoard('Sixth Board')
        cy.visit('/')
        board.findCreatedBoard()
        apiRequest.deleteBoard()
        cy.reload()
        board.deletedBoardNotExist()
    })
})
describe('Delete all boards in the workspace', () => {
    it('Delete all boards in the workspace', () => {
        apiRequest.getAllBoardsInWorkspace()
        apiRequest.deleteAllBoards()
    })
})
